# @package _global_
# configs/agents/default.yaml

defaults:
  - schema_generation
  - literature_extraction
  - structured_data_extraction
  - variable_extraction
  - knowledge_refinement
  - pseudo_point_prediction
  - literature_ranking
  - explanation
  - experiment_decomposition
  - _self_
