# @package _global_
# configs/agents/default.yaml

defaults:
  - schema_generation
  - literature_extraction
  - structured_data_extraction
  - variable_extraction
  - knowledge_refinement
  - explanation
  - _self_
